# Generated by Django 4.0.3 on 2022-03-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_app1', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
